---
# Dependabot configured for weekly Maven updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Enable version updates for Maven
  - package-ecosystem: "maven"
    directory: "/"
    # Check the registry for updates weekly
    schedule:
      interval: "weekly"
