/**
 * ============LICENSE_START=======================================================
 * org.onap.aai
 * ================================================================================
 * Copyright © 2017-2018 AT&T Intellectual Property. All rights reserved.
 * ================================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ============LICENSE_END=========================================================
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.10.28 at 05:53:17 PM EDT
//

package org.onap.aai.domain.restResponseInfo;

import org.junit.Test;

import static org.junit.Assert.assertNotNull;

public class ObjectFactoryTest {
    private ObjectFactory objectFactory = new ObjectFactory();

    @Test
    public void objectFactoryTest() {
        Info.ResponseMessages.ResponseMessage.Variables variables = objectFactory.createInfoResponseMessagesResponseMessageVariables();
        Info.ResponseMessages.ResponseMessage responseMessage = objectFactory.createInfoResponseMessagesResponseMessage();
        Info.ResponseMessages responseMessages = objectFactory.createInfoResponseMessages();
        Info info = objectFactory.createInfo();

        assertNotNull(variables);
        assertNotNull(responseMessage);
        assertNotNull(responseMessages);
        assertNotNull(info);
    }

}
