/**
 * ============LICENSE_START=======================================================
 * org.onap.aai
 * ================================================================================
 * Copyright © 2017-2018 AT&T Intellectual Property. All rights reserved.
 * ================================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ============LICENSE_END=========================================================
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.10.28 at 05:53:17 PM EDT
//

package org.onap.aai.domain.restResponseInfo;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the org.onap.aai.domain.restResponseInfo package.
 * <p>
 * An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups. Factory methods for each of these are
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes
     * for package: org.onap.aai.domain.restResponseInfo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Info }.
     *
     * @return the info
     */
    public Info createInfo() {
        return new Info();
    }

    /**
     * Create an instance of {@link Info.ResponseMessages }
     *
     * @return the response messages
     */
    public Info.ResponseMessages createInfoResponseMessages() {
        return new Info.ResponseMessages();
    }

    /**
     * Create an instance of {@link Info.ResponseMessages.ResponseMessage }
     *
     * @return the response message
     */
    public Info.ResponseMessages.ResponseMessage createInfoResponseMessagesResponseMessage() {
        return new Info.ResponseMessages.ResponseMessage();
    }

    /**
     * Create an instance of {@link Info.ResponseMessages.ResponseMessage.Variables }
     *
     * @return the variables
     */
    public Info.ResponseMessages.ResponseMessage.Variables createInfoResponseMessagesResponseMessageVariables() {
        return new Info.ResponseMessages.ResponseMessage.Variables();
    }

}
